# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
      - checkout
      
      - run:
          name: Restore Packages
          command: 
              dotnet restore
      
      - run:
          name: Build
          command: 
              dotnet build
      
      - run:
          name: Run Tests
          command: dotnet test --no-build --logger "trx;LogFileName=result.trx" --results-directory ../test-results
              
      - run:
          name: Install trx2junit
          command: |
              dotnet tool install -g trx2junit
              export PATH="$PATH:/root/.dotnet/tools"
              
      - run:
          name: Convert trx2junit        
          command: trx2junit test-results/*.trx
      
      - run:
          name: Run Terminal App
          command: 
              dotnet run -p app-terminal
                     
      - store_test_results:
          path: test-results
          
      - store_artifacts:
          path: test-results
          destination: test-results